"""add_candidate_invitations

Revision ID: eb80328db917
Revises: b20ba85ad7b3
Create Date: 2026-05-21 21:48:13.596607+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb80328db917'
down_revision: Union[str, None] = 'b20ba85ad7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_status', sa.String(length=50), nullable=False),
    sa.Column('simulated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_openings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_candidate_invitations_candidate_id'), 'candidate_invitations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_job_id'), 'candidate_invitations', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_invitations_job_id'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_candidate_id'), table_name='candidate_invitations')
    op.drop_table('candidate_invitations')
    # ### end Alembic commands ###
