"""initial_schema

Revision ID: b20ba85ad7b3
Revises: 
Create Date: 2026-05-21 01:11:00.523218+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b20ba85ad7b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_version_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_call_logs_request_id'), 'ai_call_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_session_id'), 'ai_call_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_tenant_id'), 'ai_call_logs', ['tenant_id'], unique=False)
    op.create_table('job_openings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('offer_text', sa.Text(), nullable=True),
    sa.Column('discovery_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_openings_tenant_id'), 'job_openings', ['tenant_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_versions_active_name', 'prompt_versions', ['name'], unique=True, postgresql_where='is_active = true')
    op.create_index(op.f('ix_prompt_versions_name'), 'prompt_versions', ['name'], unique=False)
    op.create_table('question_bank',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('bloque', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('opciones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('genera', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('obligatoria', sa.Boolean(), nullable=False),
    sa.Column('condicion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inferida_de', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_niche'), 'question_bank', ['niche'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('años_experiencia', sa.Integer(), nullable=True),
    sa.Column('cv_text', sa.Text(), nullable=True),
    sa.Column('cv_sha256', sa.String(length=64), nullable=True),
    sa.Column('passed_ko', sa.Boolean(), nullable=True),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_openings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_job_id'), 'candidates', ['job_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_openings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_candidate_id'), 'chat_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_job_id'), 'chat_sessions', ['job_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_status'), 'chat_sessions', ['status'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('passed_ko', sa.Boolean(), nullable=False),
    sa.Column('first_failing_ko', sa.String(length=20), nullable=True),
    sa.Column('weighted_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('normalized_score', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('ko_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative_report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_openings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_candidate_id'), 'evaluations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_evaluations_job_id'), 'evaluations', ['job_id'], unique=False)
    op.create_table('dimension_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('dimension_id', sa.String(length=10), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('evidencia', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_openings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimension_scores_candidate_id'), 'dimension_scores', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_dimension_scores_evaluation_id'), 'dimension_scores', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_dimension_scores_job_id'), 'dimension_scores', ['job_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('is_summarized', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_dimension_scores_job_id'), table_name='dimension_scores')
    op.drop_index(op.f('ix_dimension_scores_evaluation_id'), table_name='dimension_scores')
    op.drop_index(op.f('ix_dimension_scores_candidate_id'), table_name='dimension_scores')
    op.drop_table('dimension_scores')
    op.drop_index(op.f('ix_evaluations_job_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_candidate_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_chat_sessions_status'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_job_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_candidate_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_candidates_job_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_question_bank_niche'), table_name='question_bank')
    op.drop_table('question_bank')
    op.drop_index(op.f('ix_prompt_versions_name'), table_name='prompt_versions')
    op.drop_index('ix_prompt_versions_active_name', table_name='prompt_versions', postgresql_where='is_active = true')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_job_openings_tenant_id'), table_name='job_openings')
    op.drop_table('job_openings')
    op.drop_index(op.f('ix_ai_call_logs_tenant_id'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_session_id'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_request_id'), table_name='ai_call_logs')
    op.drop_table('ai_call_logs')
    # ### end Alembic commands ###
